version: '3'


networks:
 net_transcendence:
  name: net_transcendence


volumes:
 frontend_data:
  name: frontend_data
  driver: local
  driver_opts:
   type: none
   o: bind
   device: ./frontend

 backend_data:
  name: backend_data
  driver: local
  driver_opts:
   type: none
   o: bind
   device: ./backend

 db_data:
  name: db_data


services:
 frontend:
  container_name: frontend
  build: ./dockerfiles/frontend
  volumes:
   - frontend_data:/frontend
  restart: always
  networks:
   - net_transcendence

 postgresql:
  container_name: postgresql
  image: postgres
  volumes:
   - db_data:/db_data
  restart: always
  networks:
   - net_transcendence
  env_file:
   - .env

 backend:
  container_name: backend
  build: ./dockerfiles/backend
  depends_on:
   - postgresql
  volumes:
   - backend_data:/backend
  restart: always
  networks:
   - net_transcendence
  env_file:
   - .env

 adminer:
  container_name: adminer
  image: adminer
  restart: always
  depends_on:
   - postgresql
  networks:
   - net_transcendence

 nginx:
  container_name: nginx
  build: ./dockerfiles/nginx
  restart: always
  depends_on:
   - frontend
   - backend
  networks:
   - net_transcendence
  ports:
   - "4200:80"
