version: '3'


networks:
 net_transcendence:
  name: net_transcendence


volumes:
 backend_data:
  name: backend_data
  driver: local
  driver_opts:
   type: none
   o: bind
   device: $PWD/backend

 db_data:
  name: db_data


services:
 postgresql:
  container_name: postgresql
  image: postgres
  volumes:
   - db_data:/db_data
  restart: always
  networks:
   - net_transcendence
  env_file:
   - .env

 backend:
  container_name: backend
  build: ./dockerfiles/backend
  depends_on:
   - postgresql
  volumes:
   - backend_data:/backend
  restart: always
  networks:
   - net_transcendence
  env_file:
   - .env
  ports:
   - "4200:8000"
   - "8765:8765"
  #  Ports for game servers
   - "8766:8766"
   - "8767:8767"
   - "8768:8768"
   - "8769:8769"
   - "8770:8770"

 adminer:
  container_name: adminer
  image: adminer
  restart: always
  depends_on:
   - postgresql
  networks:
   - net_transcendence
  ports:
   - "8080:8080"
