# Generated by Django 4.2.7 on 2023-11-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connection42',
            fields=[
                ('login', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
            ],
        ),
    ]
