# Generated by Django 4.2.6 on 2024-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db_test", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchuser",
            old_name="mabBallBounce",
            new_name="maxBallBounce",
        ),
    ]
