# Generated by Django 4.2.7 on 2023-11-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('idType', models.IntegerField()),
                ('username', models.CharField(max_length=10, unique=True)),
                ('profilPicture', models.TextField()),
                ('tokenJWT', models.TextField()),
                ('money', models.IntegerField()),
                ('idStatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='connectionPassword',
            fields=[
                ('idPassword', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_test.user')),
            ],
        ),
        migrations.AlterField(
            model_name='connection42',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_test.user'),
        ),
    ]
