# Generated by Django 5.0.2 on 2024-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchuser',
            name='idPaddle',
            field=models.IntegerField(default=0),
        ),
    ]
