# Generated by Django 5.0.2 on 2024-02-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchuser',
            old_name='mabBallBounce',
            new_name='idTeam',
        ),
        migrations.AddField(
            model_name='goal',
            name='idTeam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='nbMaxBallOnGame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchuser',
            name='maxBallBounce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nbTournamentWin',
            field=models.IntegerField(default=0),
        ),
    ]
