# Generated by Django 5.0.2 on 2024-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0002_rename_mabballbounce_matchuser_maxballbounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchuser',
            name='idTeam',
            field=models.IntegerField(default=0),
        ),
    ]
