# Generated by Django 4.2.7 on 2023-11-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0002_user_connectionpassword_alter_connection42_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('forKarl', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('goalTimer', models.TimeField()),
                ('idMatch', models.IntegerField()),
                ('nbBounce', models.IntegerField()),
                ('perfectedShot', models.BooleanField()),
                ('ballSpeed', models.IntegerField()),
                ('ownGoal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('idMap', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('background', models.TextField()),
                ('obstacle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('idMatch', models.IntegerField(primary_key=True, serialize=False)),
                ('matchDate', models.TimeField()),
                ('matchDuration', models.TimeField()),
                ('idMap', models.IntegerField()),
                ('powerUp', models.BooleanField()),
                ('cursed', models.BooleanField()),
                ('tournament', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchTournament',
            fields=[
                ('idMatch', models.IntegerField(primary_key=True, serialize=False)),
                ('idTournament', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idMatch', models.IntegerField()),
                ('idUser', models.IntegerField()),
                ('score', models.IntegerField()),
                ('powerUp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('date', models.TimeField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('date', models.TimeField()),
                ('data', models.TextField()),
                ('idTarget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('idTournament', models.IntegerField(primary_key=True, serialize=False)),
                ('startDate', models.TimeField()),
                ('nameTournament', models.CharField(max_length=20)),
                ('nbMaxUser', models.IntegerField()),
                ('idMap', models.IntegerField()),
                ('powerUp', models.BooleanField()),
                ('cursed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idTournament', models.IntegerField()),
                ('idUser', models.IntegerField()),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('idType', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='connection42',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user', unique=True),
        ),
        migrations.AlterField(
            model_name='connectionpassword',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user', unique=True),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idTarget', models.IntegerField()),
                ('link', models.IntegerField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user')),
            ],
        ),
    ]
