# Generated by Django 5.0.2 on 2024-02-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0002_rename_mabballbounce_matchuser_idteam_goal_idteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tokenJWT',
        ),
    ]
