# Generated by Django 5.0.2 on 2024-02-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0003_remove_user_tokenjwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchDate',
            field=models.TextField(),
        ),
    ]
