# Generated by Django 5.0.2 on 2024-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0003_goal_idteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='nbMaxBallOnGame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchuser',
            name='idTeam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nbTournamentWin',
            field=models.IntegerField(default=0),
        ),
    ]
