# Generated by Django 4.2.7 on 2023-11-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0003_achivement_goal_linktype_map_match_matchtournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection42',
            name='idUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
        migrations.AlterField(
            model_name='connectionpassword',
            name='idUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
    ]
