# Generated by Django 4.2.7 on 2023-11-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0004_alter_connection42_iduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='idUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db_test.user'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='idMatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.match'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.linktype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='idMap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.map'),
        ),
        migrations.AlterField(
            model_name='matchtournament',
            name='idMatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db_test.match'),
        ),
        migrations.AlterField(
            model_name='matchtournament',
            name='idTournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.tournament'),
        ),
        migrations.AlterField(
            model_name='matchuser',
            name='idMatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.match'),
        ),
        migrations.AlterField(
            model_name='matchuser',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
        migrations.AlterField(
            model_name='privmessage',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='idMap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.map'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.status'),
        ),
        migrations.AlterField(
            model_name='usertournament',
            name='idTournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.tournament'),
        ),
        migrations.AlterField(
            model_name='usertournament',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_test.user'),
        ),
    ]
