# Generated by Django 5.0.1 on 2024-02-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0004_alter_match_matchdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchuser',
            name='idPaddle',
            field=models.IntegerField(default=0),
        ),
    ]
