# Generated by Django 4.2.7 on 2023-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0005_alter_achivement_iduser_alter_goal_idmatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtournament',
            name='idMatch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db_test.match'),
        ),
    ]
