# Generated by Django 5.0.1 on 2024-01-15 13:08

import db_test.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0006_alter_matchtournament_idmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilPicture',
            field=models.ImageField(upload_to='images/', validators=[db_test.validators.validate_file_size], verbose_name=''),
        ),
    ]
