# Generated by Django 5.0.1 on 2024-01-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0007_alter_user_profilpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.IntegerField(),
        ),
    ]
