# Generated by Django 5.0.1 on 2024-01-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0008_alter_link_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkType',
        ),
    ]
