# Generated by Django 5.0.1 on 2024-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0009_delete_linktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idStatus',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
