# Generated by Django 5.0.2 on 2024-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0011_remove_achivement_forkarl_achivement_boscofriend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
