# Generated by Django 5.0.2 on 2024-02-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0011_remove_achivement_forkarl_achivement_boscofriend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='nameTournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='nbMaxUser',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='startDate',
        ),
    ]
