# Generated by Django 5.0.2 on 2024-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0012_remove_tournament_nametournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
