# Generated by Django 5.0.2 on 2024-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0012_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achivement',
            old_name='molyBatle',
            new_name='molyBattle',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='nbMaxUser',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idType',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='map',
            name='background',
        ),
        migrations.RemoveField(
            model_name='map',
            name='obstacle',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='cursed',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='nameTournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='startDate',
        ),
    ]
