# Generated by Django 4.2.6 on 2024-02-11 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db_test", "0013_rename_molybatle_achivement_molybattle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="idMap",
        ),
        migrations.RemoveField(
            model_name="usertournament",
            name="idTournament",
        ),
        migrations.RemoveField(
            model_name="usertournament",
            name="idUser",
        ),
        migrations.DeleteModel(
            name="MatchTournament",
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
        migrations.DeleteModel(
            name="UserTournament",
        ),
    ]
