# Generated by Django 4.2.6 on 2024-02-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_test", "0014_remove_tournament_idmap_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="cursed",
        ),
        migrations.RemoveField(
            model_name="match",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="matchuser",
            name="powerUp",
        ),
        migrations.AddField(
            model_name="match",
            name="type",
            field=models.IntegerField(default=0),
        ),
    ]
