# Generated by Django 4.2.6 on 2024-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_test", "0017_alter_match_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="type",
            field=models.IntegerField(),
        ),
    ]
